name: CI
on: [push]
jobs:
  standard-checks:
    name: Format, Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # https://docs.npmjs.com/cli/v7/commands/npm-ci
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: npm run ci-prettier
      - name: Linting
        run: npm run ci-lint
      - name: Run Tests
        run: npm run ci-test
